apiVersion: v1
kind: ServiceList
items:
  - apiVersion: v1
    kind: Service
    metadata:
      namespace: nsolid
      name: nsolid-registry
    spec:
      ports:
        - port: 2379
          targetPort: clientport
      selector:
        app: nsolid-registry
  - apiVersion: v1
    kind: Service
    metadata:
      namespace: nsolid
      name: nsolid-proxy
    spec:
      sessionAffinity: None
      ports:
        - port: 9000
          targetPort: proxy
      selector:
        app: nsolid-proxy
  - apiVersion: v1
    kind: Service
    metadata:
      namespace: nsolid
      name: nsolid-console
    spec:
      sessionAffinity: ClientIP
      type: LoadBalancer
      ports:
        - port: 80
          targetPort: console
      selector:
        app: nsolid-console
  - apiVersion: v1
    kind: Service
    metadata:
      namespace: nsolid
      name: cluster-proxy
      labels:
        app: cluster-proxy
    spec:
      type: LoadBalancer
      ports:
        - name: http
          protocol: TCP
          port: 80
          targetPort: 80
        - name: https
          protocol: TCP
          port: 443
          targetPort: 443
      selector:
        app: cluster-proxy
