apiVersion: v1
kind: ReplicationController
metadata:
  name: nsolid-proxy
  labels:
    app: nsolid-proxy
spec:
  replicas: 1
  selector:
    app: nsolid-proxy
  template:
    metadata:
      labels:
        app: nsolid-proxy
    spec:
      containers:
        - name: proxy
          image: "nodesource/nsolid-hub:v3.4.2"
          args:
            - --registry=nsolid-registry:4001
          env:
            - name: NSOLID_APPNAME
              value: nsolid-proxy
            - name: NSOLID_HUB
              value: "nsolid-registry:4001"
            - name: NSOLID_SOCKET
              value: "8000"
          ports:
            - containerPort: 9000
              name: proxy
            - containerPort: 8000
              name: nsolid
