apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-app
  labels:
    app: sample-app
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: sample-app
          image: sample-app:v1
          env:
            - name: NSOLID_APPNAME
              value: sample-app
            - name: NSOLID_HUB
              value: "nsolid-registry.nsolid:2379"
            - name: NSOLID_SOCKET
              value: "8000"
            - name: NSOLID_TAGS
              value: "nsolid-v1.4.0"
            - name: PORT
              value: "4444"
          ports:
            - containerPort: 4444
              name: sample-app
            - containerPort: 8000
              name: nsolid
