 apiVersion: v1
 kind: PersistentVolumeList
 items:
   - apiVersion: v1
     kind: PersistentVolume
     metadata:
       name: nsolid-registry
     spec:
      capacity:
        storage: 10Gi
      accessModes:
        - ReadWriteOnce
        - ReadOnlyMany
      gcePersistentDisk:
        pdName: "nsolid-registry"
        fsType: "ext4"
   - apiVersion: v1
     kind: PersistentVolume
     metadata:
       name: nsolid-console
     spec:
      capacity:
        storage: 10Gi
      accessModes:
        - ReadWriteOnce
        - ReadOnlyMany
      gcePersistentDisk:
        pdName: "nsolid-console"
        fsType: "ext4"
---
apiVersion: v1
kind: PersistentVolumeClaimList
items:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      namespace: nsolid
      name: nsolid-registry
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      namespace: nsolid
      name: nsolid-console
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
